# @package hydra.sweeper
# Tune MLP hyperparams with declarative search space definitions.
study_name: mlp_hpo
params:
  model.learning_rate_init: tag(log, interval(1e-4, 1e-1))
  model.alpha: tag(log, interval(1e-5, 1e-1))
  model.activation: choice(relu, tanh, logistic)
