# Full list of kwargs:
# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
_target_: sklearn.ensemble.RandomForestClassifier
n_estimators: 100
criterion: gini
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
max_features: sqrt
random_state: ${seed}
class_weight:
